# Generated by Django 4.2.1 on 2023-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_produit_vente_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite_disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite_vendue',
            field=models.PositiveIntegerField(),
        ),
    ]
