# Generated by Django 4.2.1 on 2023-06-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_vente_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
