# Generated by Django 4.2.1 on 2023-06-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0005_vente_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='prix_unitaire',
        ),
    ]
