# Generated by Django 4.2.1 on 2023-06-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0006_remove_vente_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
