# Generated by Django 4.2.1 on 2023-06-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0007_vente_prix_unitaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom_produit',
            new_name='produit',
        ),
    ]
