# Generated by Django 4.2.1 on 2023-06-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0008_rename_nom_produit_produit_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='prix_unitaire',
        ),
    ]
